-- AVG: GERAR MEDIA DOS DADOS
-- SUM: SOMANDO DADOS DE UM COLUNA
-- COUNT: CONTAR REGISTROS
-- MAX E MIN: PEGAR VALORES MAXIMOS E MINIMOS
-- UPPER E LOWER: CONVERTER TEXTO P/ MAIUSCULO E MINUSCULO

-- ###### AVG ######

SELECT * FROM ALUNOS;

-- ADICIONAR A COLUNA PESO
ALTER TABLE ALUNOS ADD PESO NUMBER;

-- ATUALIZAR A COLUNA PESO DE CADA REGISTRO
UPDATE ALUNOS
SET PESO = 100
WHERE ID_ALUNO = 1;

-- VER A MEDIA DE TODOS OS REGISTROS DA COLUNA PESO
SELECT AVG(PESO) FROM ALUNOS;

-- VER A MEDIA DO PESO SOMENTE DO ID_ALUNO 1 A 3
SELECT AVG(PESO) FROM ALUNOS WHERE ID_ALUNO BETWEEN 1 AND 3;

-- ###### SUM ######

SELECT * FROM ALUNOS;

-- SOMANDO TODOS OS VALORES DA COLUNA PESO
SELECT SUM(PESO) FROM ALUNOS;

-- PODEMOS DAR NOME AS COLUNAS COM AJUDA DO AS
SELECT SUM(PESO) AS TOTAL_PESO FROM ALUNOS;

-- ###### COUNT ######

-- CONTANDO O TOTAL DE REGISTROS DA TABELA ALUNOS
SELECT COUNT(*) FROM ALUNOS;

-- CONTANDO TODOS OS REGISTROS DA COLUNA NOME_ALUNO
SELECT COUNT(NOME_ALUNO) FROM ALUNOS;

-- ###### MAX E MIN ######

SELECT * FROM ALUNOS;

-- PEGANDO O VALOR MAXIMO DA COLUNA PESO
SELECT MAX(PESO) FROM ALUNOS;

-- PEGANDO O VALOR MINIMO DA COLUNA PESO
SELECT MIN(PESO) FROM ALUNOS;

-- ATENCAO: PODEMOS PEGAR O VALOR MAXIMO E MINIMO DE TEXTOS
SELECT MAX(NOME_ALUNO) FROM ALUNOS;
SELECT MIN(NOME_ALUNO) FROM ALUNOS;

-- ###### UPPER E LOWER ######

-- TRANSFORMANDO A COLUNA NOME_ALUNO EM MINUSCULO
SELECT LOWER(NOME_ALUNO) FROM ALUNOS;

-- TRANSFORMANDO A COLUNA NOME_ALUNO EM MAIUSCULO
SELECT UPPER(NOME_ALUNO) FROM ALUNOS;
