-- SYSDATE: RELÓGIO DE PULSO DO SEU BANCO DE DADOS. SEMPRE QUE VOCÊ O CONSULTA, ELE TE DIZ EXATAMENTE QUE DIA E QUE HORAS SÃO NAQUELE EXATO MOMENTO.

SELECT SYSDATE FROM DUAL;

SELECT * FROM VENDAS;

INSERT INTO VENDAS (ID_CLIENTE, DATA_VENDA)
VALUES (112, SYSDATE);

SELECT * FROM VENDAS;


-- TO_DATE: ELA CONVERTE UMA STRING EM UM DADO DO TIPO DATE.
 
-- A SINTAXE É:
-- TO_DATE('TEXTO', 'FORMATO')

-- O FORMATO É A PARTE MAIS IMPORTANTE. OS CÓDIGOS MAIS COMUNS SÃO:
 
-- DD: DIA COM DOIS DIGITOS - 01, 02, 15
-- MM: MÊS COM DOIS DIGITOS - 01, 07, 12
-- YYYY: ANO COM QUATRO DIGITOS - 1990, 2025

INSERT INTO CLIENTES (NOME, DATA_NASCIMENTO)
VALUES ('JOAO', TO_DATE('15/10/1990', 'DD/MM/YYYY'));

SELECT * FROM CLIENTES;


-- TO_CHAR: PEGA UMA DATA QUE JÁ ESTÁ NO FORMATO DO ORACLE E A CONVERTE PARA UM TEXTO, ESTILIZADO DA FORMA QUE VOCÊ MANDAR.
 
-- A SINTAXE É:
-- TO_CHAR(COLUNA_DE_DATA, 'FORMATO_DE_SAÍDA’)

SELECT
  DATA_NASCIMENTO,
  TO_CHAR(DATA_NASCIMENTO, 'DD/MM/YYYY') AS FORMATO_BR,
  TO_CHAR(DATA_NASCIMENTO, 'YYYY-MM-DD') AS FORMATO_ISO,
  TO_CHAR(DATA_NASCIMENTO, 'Day, DD "de" Month') AS POR_EXTENSO
FROM CLIENTES
WHERE ID = 1;


-- RESUMO
 
-- SYSDATE: Pega a data e hora de agora, direto do servidor. Perfeito para logs e registros de transações.
 
-- TO_DATE: O tradutor. Converte um TEXTO para o formato de DATA do Oracle. Use-o sempre no INSERT e UPDATE para garantir que os dados estão corretos.
 
-- TO_CHAR: O estilista. Converte uma DATA do Oracle para um TEXTO formatado. Perfeito para a cláusula SELECT quando você quer exibir os dados de um jeito específico.
