-- ROUND: SERVE PARA ARREDONDAR NUMEROS

-- SINTAXE:
-- ROUND(COLUNA, QUANTIDADE_CASAS_DECIMAIS)

SELECT * FROM PRODUTOS;

SELECT PRODUTO, PRECO, ROUND(PRECO, 2) AS PRECO_ARREDONDADO FROM PRODUTOS;

-- OBS: SE NÃO PASSAR O NUMERO DE CASAS DECIMAIS, ELE ARREDONDA PARA O NUMERO INTEIRO MAIS PROXIMO


-- TRUNC: DE TRUNCAR. ELE SIMPLESMENTE CORTA AS CASAS DECIMAIS

-- SINTAXE:
-- TRUNC(COLUNA, QUANTIDADE_CASAS_DECIMAIS)

SELECT PRODUTO, PRECO, TRUNC(PRECO, 1) AS PRECO_TRUNC FROM PRODUTOS;

-- OBS: SE USAR TRUNC(PRECO), SEM O NUMERO DE CASAS, ELE REMOVE TODA A PARTE DECIMAL
-- TE DANDO SO A PARTE INTEIRA DO NUMERO


-- MOD: RETORNA O RESTO DE UMA DIVISAO

-- SINTAXE:
-- MOD(NUMERO OU COLUNA, NUMERO_PELO_QUAL_DIVIDIR)

SELECT * FROM PEDIDOS;

SELECT ID_PEDIDO, MOD(ID_PEDIDO, 2) AS RESTO_DA_DIVISAO_POR_2 FROM PEDIDOS;


-- RECAPITULAR

-- ROUND: O ARREDONDADOR JUSTO. OTIMO PARA MOSTRAR PRECOS E VALORES DE FORMA AMIGAVEL.

-- TRUNC: O CORTADOR. SIMPLESMENTE JOGA FORA AS CASAS DECIMAIS, SEM ANALISAR NADA.

-- MOD: O DETETIVE DO RESTO. INCRIVEL P/ DESCOBRIR SE UM NUMERO É PAR OU ÍMPAR.
