-- LENGTH: CONTA QUANTOS CARACTERES EXISTEM DENTRO DE UM TEXTO

SELECT * FROM PRODUTOS;

-- SINTAXE:
-- LENGTH(COLUNA)

SELECT
    NOME,
    LENGTH(NOME) AS TAMANHO_DO_NOME
FROM
    PRODUTOS;

-- INSTR: ELA NOS AJUDA A ENCONTRAR A POSICAO DE UM CARACTERE DENTRO DE OUTRO TEXTO

SELECT * FROM CLIENTES;

-- SINTAXE:
-- INSTR(COLUNA,TEXTO_QUE_VOCE_PROCURA)

SELECT 
    EMAIL,
    INSTR(EMAIL,'@') AS POSICAO_DO_ARROBA
FROM
    CLIENTES;

-- SUBSTR: COM ELA, A GENTE CONSEGUE CORTAR E PEGAR APENAS UM PEDACO DE UM TEXTO

SELECT * FROM PRODUTOS;

-- A SINTAXE DELA TEM 3 PARTES
-- SUBSTR(COLUNA,DE_ONDE_COMECAR,QUANTOS_CARACTERES_PEGAR)

SELECT
    NOME,
    SUBSTR(NOME,1,3) AS INICIAIS
FROM
    PRODUTOS;

-- OBS: O TERCEIRO ARGUMENTO É OPCIONAL. SE VOCE NAO COLOCAR, ELE PEGA TUDO DO
-- INICIO ATE O FINAL DO TEXTO

-- VAMOS JUNTAR INSTR E SUBSTR PARA RESOLVER UM PROBLEMA REAL

-- USANDO NOSSA TABELA DE CLIENTES, EU QUERO EXTRAIR APENAS O NOME DE USUARIO
-- DE CADA EMAIL, OU SEJA, TUDO O QUE VEM ANTES DO @

-- PRIMEIRO, USAMOS O INSTR PARA DESCOBRIR A POSICAO DO @

-- DEPOIS, USAMOS O SUBSTR PARA PEGAR O TEXTO, COMEÇANDO DA POSICAO 1 ATÉ A
-- POSICAO ANTES DO @

SELECT
    EMAIL,
    SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1) AS USUARIO
FROM
    CLIENTES
WHERE
    EMAIL IS NOT NULL;

-- RECAPITULANDO

-- LENGTH: CONTA O TAMANHO DE UM TEXTO

-- INSTR: ENCONTRA A POSICAO DE UM CARACTERE

-- SUBSTR: EXTRAI UM PEDAÇO DE UM TEXTO
