-- ###### CONCATENANDO COLUNAS COM O PIPE || ######

-- CONCATENAR SIGNIFICA JUNTAR

SELECT * FROM ALUNOS;

SELECT NOME_ALUNO, CIDADE_ALUNO FROM ALUNOS;

SELECT NOME_ALUNO || CIDADE_ALUNO FROM ALUNOS;

SELECT NOME_ALUNO || CIDADE_ALUNO AS NOME_CIDADE FROM ALUNOS;

SELECT NOME_ALUNO || '-' ||CIDADE_ALUNO AS NOME_CIDADE FROM ALUNOS;

SELECT NOME_ALUNO || ' ' ||CIDADE_ALUNO AS NOME_CIDADE FROM ALUNOS;

-- ###### MODIFICANDO TAMANHO/TIPO DA COLUNA COM ALTER TABLE MODIFY ######

DESC ALUNOS;

-- AUMENTAR O TAMANHO DA COLUNA CIDADE_ALUNO PARA 50
ALTER TABLE ALUNOS MODIFY CIDADE_ALUNO VARCHAR2(50);

-- ALTERANDO O TIPO DA COLUNA DATA_NASC_ALUNO PARA VARCHAR
ALTER TABLE ALUNOS MODIFY DATA_NASC_ALUNO VARCHAR2(15);

SELECT * FROM ALUNOS;

-- ###### APAGANDO UMA COLUNA DA TABELA COM ALTER TABLE DROP ######

SELECT * FROM ALUNOS;

-- APAGAR A COLUNA PESO
ALTER TABLE ALUNOS DROP (PESO);

-- ###### DELETAR REGISTROS DA TABELA COM DELETE ######

SELECT * FROM ALUNOS;

-- DELETAR O REGISTRO EM QUE O ID_ALUNO É IGUAL A 1
DELETE FROM ALUNOS WHERE ID_ALUNO = 1;

-- ATENCAO: O DELETE PODE SER DESFEITO COM O ROLLBACK
ROLLBACK;

-- APOS DELETAR, EXECUTE O COMMIT SE VOCE DESEJA SALVAR ESSA ACAO
COMMIT;

-- ###### EXCLUIR TABELA COM DROP TABLE ######

-- PRIMEIRO IREMOS CRIAR UMA NOVA TABELA
CREATE TABLE ESCOLAS (
    ID_ESCOLA NUMBER,
    NOME_ESCOLA VARCHAR2(50),
    CNPJ_ESCOLA NUMBER
);

SELECT * FROM ESCOLAS;

DESC ESCOLAS;

-- INSERIR REGISTROS NA TABELA ESCOLAS
INSERT INTO ESCOLAS (ID_ESCOLA, NOME_ESCOLA, CNPJ_ESCOLA) 
VALUES (1,'PALAS ATENAS',12312344);

-- EXCLUIR A TABELA ESCOLAS
DROP TABLE ESCOLAS;


















