-- FOREIGN KEY: É UMA COLUNA NUMA TABELA QUE APONTA PARA A CHAVE PRIMARIA DE OUTRA TABELA. 

-- ELA CRIA UMA LIGACAO ENTRE AS TABELAS.

-- VAMOS VER OS REGISTROS DAS TABELAS
SELECT * FROM CIDADES;
SELECT * FROM ALUNOS;

-- VEJA QUE NA TABELA ALUNOS EXISTE A COLUNA CIDADE COM OS NOMES DAS CIDADES.
-- IREMOS EXCLUIR ESSA COLUNA PARA USARMOS OS CODIGOS DAS CIDADES E NÃO OS NOMES.
ALTER TABLE ALUNOS DROP COLUMN CIDADE_ALUNO;

-- AGORA IREMOS INSERIR A COLUNA CIDADE_ID
ALTER TABLE ALUNOS ADD CIDADE_ID NUMBER;

-- ADICIONANDO A REGRA: COLUNA CIDADE_ID AGORA É UMA FOREIGN KEY  
-- VAMOS ENTENDER O QUE CADA LINHA SIGNIFICA
-- LEMBRANDO QUE VOCÊ PODE JOGAR ESSE CÓDIGO NO CHATGPT E PEDIR P/ ELE EXPLICAR DE MANEIRA SIMPLES
ALTER TABLE ALUNOS            -- QUERO ALTERAR A TABELA ALUNOS
ADD CONSTRAINT FK_CIDADE_ID   -- VOU CRIAR UMA REGRA CHAMADA FK_CIDADE_ID
FOREIGN KEY (CIDADE_ID)       -- A COLUNA CIDADE_ID SERÁ UMA FOREIGN KEY
REFERENCES CIDADES (ID_CID);  -- A COLUNA CIDADE_ID DEVE USAR OS VALORES CONTIDOS NA COLUNA ID_CID DA TABELA CIDADES

-- VAMOS OLHAR AS TABELAS
SELECT * FROM ALUNOS;
SELECT * FROM CIDADES;

-- AGORA VAMOS INSERIR DADOS APENAS NA COLUNA CIDADE_ID DA TABELA ALUNOS 
-- O CODIGO QUE IREMOS INSERIR DEVE EXISTIR NA TABELA CIDADES
UPDATE ALUNOS
SET CIDADE_ID = 1  
WHERE ID_ALU = 1;
