-- DESCRIBE OU DESC: OBTEM INFORMACOES DA TABELA
-- ALTER TABLE ADD: ADICIONA UMA NOVA COLUNA NA TABELA
-- DISTINCT: ELIMINA REGISTROS DUPLICADOS

-- ## DESCRIBE ##

DESCRIBE ALUNOS;

DESC ALUNOS;

-- ## ALTER TABLE ADD ##

-- ADICIONAR A COLUNA CIDADE NA TABELA ALUNOS

-- LÊ-SE: ALTERAR A TABELA ALUNOS / ADICIONAR A COLUNA CIDADE
ALTER TABLE ALUNOS ADD CIDADE_ALUNO VARCHAR2(20);

-- VER COMO FICOU
SELECT * FROM ALUNOS;

-- INSERIR DADOS NA COLUNA CIDADE_ALUNO
INSERT INTO ALUNOS (CIDADE_ALUNO) VALUES ('MANAUS') WHERE ID_ALUNO = 1;
INSERT INTO ALUNOS (CIDADE_ALUNO) VALUES ('RECIFE') WHERE ID_ALUNO = 2;
INSERT INTO ALUNOS (CIDADE_ALUNO) VALUES ('MANAUS') WHERE ID_ALUNO = 3;
INSERT INTO ALUNOS (CIDADE_ALUNO) VALUES ('PARINTINS') WHERE ID_ALUNO = 4;
INSERT INTO ALUNOS (CIDADE_ALUNO) VALUES ('TABATINGA') WHERE ID_ALUNO = 5;

-- VER COMO FICOU
SELECT * FROM ALUNOS;

-- ## DISTINCT ##

-- COM ESSE SELECT QUEREMOS VER APENAS A COLUNA CIDADE_ALUNO
-- PODEMOS VER QUE TEMOS 2 CIDADES SE REPETINDO
SELECT CIDADE_ALUNO FROM ALUNOS;

-- COM O DISTINCT PODEMOS REMOVER AS DUPLICIDADES
SELECT DISTINCT(CIDADE_ALUNO) FROM ALUNOS; 

-- ATENCAO: AS DUPLICIDADES NAO SERAO REMOVIDAS DA TABELA
-- SOMENTE NA NOSSA CONSULTA
SELECT * FROM ALUNOS;


